import type {
  AIAnalysis,
  Challenge,
  ChallengeDetail,
  DashboardData,
  DuplicateCluster,
  ImpactSummary,
  MapData,
  PriorityScore,
  ProblemReport,
  Project,
  SolverMatch,
  Solution,
  SubmitProblemData,
} from '@/types';

const now = new Date();
const daysAgo = (n: number) =>
  new Date(now.getTime() - n * 86400000).toISOString();

export const mockReports: ProblemReport[] = [
  {
    id: 'rpt-001',
    title: 'Heavy Rainfall Causes Severe Waterlogging on Main Road',
    description:
      'Heavy rainfall causes severe waterlogging and road inaccessibility near XYZ locality, affecting approximately 2,500 residents and restricting access to schools, healthcare and public transport.',
    category: 'Infrastructure',
    subcategory: 'Drainage / Road Accessibility',
    urgency: 'HIGH',
    affectedPopulation: 2500,
    location: { lat: 23.3441, lng: 85.3096, name: 'Main Road, Ranchi', district: 'Ranchi' },
    evidence: [
      { id: 'e1', type: 'image', url: '', name: 'flooded_road_1.jpg' },
      { id: 'e2', type: 'image', url: '', name: 'waterlogging_2.jpg' },
    ],
    status: 'ANALYZED',
    challengeId: 'ch-001',
    createdAt: daysAgo(5),
    reporterName: 'Ravi Kumar',
  },
  {
    id: 'rpt-002',
    title: 'Road completely flooded after yesterday rain',
    description:
      'The entire main road is flooded. No vehicles can pass. Children cannot go to school.',
    category: 'Infrastructure',
    subcategory: 'Drainage',
    urgency: 'HIGH',
    affectedPopulation: 1800,
    location: { lat: 23.346, lng: 85.31, name: 'Main Road, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e3', type: 'image', url: '', name: 'flood.jpg' }],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 94,
    distance: '0.3 km',
    createdAt: daysAgo(4),
    reporterName: 'Priya Sharma',
  },
  {
    id: 'rpt-003',
    title: 'Children unable to reach school because of waterlogging',
    description:
      'Waterlogging on the main road is preventing children from reaching school safely.',
    category: 'Infrastructure',
    subcategory: 'Road Accessibility',
    urgency: 'HIGH',
    affectedPopulation: 600,
    location: { lat: 23.342, lng: 85.308, name: 'School Road, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e4', type: 'image', url: '', name: 'school_road.jpg' }],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 91,
    distance: '0.5 km',
    createdAt: daysAgo(3),
    reporterName: 'Anita Devi',
  },
  {
    id: 'rpt-004',
    title: 'Main road blocked during rainfall',
    description: 'The main road gets blocked every time it rains heavily.',
    category: 'Infrastructure',
    subcategory: 'Drainage',
    urgency: 'MEDIUM',
    affectedPopulation: 1200,
    location: { lat: 23.345, lng: 85.312, name: 'Main Road, Ranchi', district: 'Ranchi' },
    evidence: [],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 89,
    distance: '0.2 km',
    createdAt: daysAgo(3),
    reporterName: 'Mohan Singh',
  },
  {
    id: 'rpt-005',
    title: 'No proper drainage system in our area',
    description: 'There is no drainage system. Water accumulates for days.',
    category: 'Water & Sanitation',
    subcategory: 'Drainage',
    urgency: 'MEDIUM',
    affectedPopulation: 800,
    location: { lat: 23.35, lng: 85.32, name: 'Sector 4, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e5', type: 'image', url: '', name: 'drain.jpg' }],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 87,
    distance: '0.8 km',
    createdAt: daysAgo(2),
    reporterName: 'Suresh Paswan',
  },
  {
    id: 'rpt-006',
    title: 'Hospital road flooded, ambulances stuck',
    description: 'The road to the district hospital floods, blocking ambulances.',
    category: 'Healthcare',
    subcategory: 'Accessibility',
    urgency: 'CRITICAL',
    affectedPopulation: 5000,
    location: { lat: 23.36, lng: 85.33, name: 'Hospital Road, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e6', type: 'image', url: '', name: 'hospital_road.jpg' }],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 85,
    distance: '1.2 km',
    createdAt: daysAgo(2),
    reporterName: 'Dr. K Verma',
  },
  {
    id: 'rpt-007',
    title: 'Public transport disrupted due to waterlogging',
    description: 'Buses cannot operate on the main road due to waterlogging.',
    category: 'Transport',
    subcategory: 'Road Transport',
    urgency: 'HIGH',
    affectedPopulation: 3000,
    location: { lat: 23.343, lng: 85.311, name: 'Bus Stand, Ranchi', district: 'Ranchi' },
    evidence: [],
    status: 'MERGED',
    challengeId: 'ch-001',
    similarity: 83,
    distance: '0.4 km',
    createdAt: daysAgo(1),
    reporterName: 'Lakshmi Rao',
  },
  {
    id: 'rpt-008',
    title: 'Street lights not working on main road',
    description: 'Street lights have been out for 2 weeks on the main road.',
    category: 'Public Safety',
    subcategory: 'Street Lighting',
    urgency: 'LOW',
    affectedPopulation: 400,
    location: { lat: 23.34, lng: 85.305, name: 'Main Road, Ranchi', district: 'Ranchi' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Arjun Mehta',
  },
  {
    id: 'rpt-009',
    title: 'Garbage not collected in our neighborhood',
    description: 'Garbage has not been collected for over a week.',
    category: 'Waste Management',
    subcategory: 'Collection',
    urgency: 'MEDIUM',
    affectedPopulation: 700,
    location: { lat: 23.37, lng: 85.34, name: 'Sector 7, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e7', type: 'image', url: '', name: 'garbage.jpg' }],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Geeta Kumari',
  },
  {
    id: 'rpt-010',
    title: 'School building needs urgent repair',
    description: 'The school building has cracks and needs urgent repair.',
    category: 'Education',
    subcategory: 'Infrastructure',
    urgency: 'HIGH',
    affectedPopulation: 450,
    location: { lat: 22.8046, lng: 86.2029, name: 'Govt School, Jamshedpur', district: 'Jamshedpur' },
    evidence: [{ id: 'e8', type: 'image', url: '', name: 'school.jpg' }],
    status: 'ANALYZED',
    challengeId: 'ch-002',
    createdAt: daysAgo(6),
    reporterName: 'Rajesh Tiwari',
  },
  {
    id: 'rpt-011',
    title: 'Contaminated drinking water supply',
    description: 'The water supply is contaminated and causing illness.',
    category: 'Water & Sanitation',
    subcategory: 'Water Quality',
    urgency: 'CRITICAL',
    affectedPopulation: 3200,
    location: { lat: 23.7956, lng: 86.4304, name: 'Colony 3, Dhanbad', district: 'Dhanbad' },
    evidence: [{ id: 'e9', type: 'image', url: '', name: 'water.jpg' }],
    status: 'ANALYZED',
    challengeId: 'ch-003',
    createdAt: daysAgo(4),
    reporterName: 'Nisha Gupta',
  },
  {
    id: 'rpt-012',
    title: 'Air pollution from factory affecting residents',
    description: 'A nearby factory is emitting heavy smoke affecting health.',
    category: 'Environment',
    subcategory: 'Air Pollution',
    urgency: 'HIGH',
    affectedPopulation: 5000,
    location: { lat: 23.7894, lng: 86.4238, name: 'Industrial Area, Dhanbad', district: 'Dhanbad' },
    evidence: [{ id: 'e10', type: 'image', url: '', name: 'pollution.jpg' }],
    status: 'ANALYZED',
    challengeId: 'ch-004',
    createdAt: daysAgo(5),
    reporterName: 'Amit Prasad',
  },
  {
    id: 'rpt-013',
    title: 'No bus service to remote village',
    description: 'Our village has no public transport connecting to the city.',
    category: 'Transport',
    subcategory: 'Public Transport',
    urgency: 'MEDIUM',
    affectedPopulation: 1500,
    location: { lat: 23.6, lng: 85.8, name: 'Rural Block, Bokaro', district: 'Bokaro' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(2),
    reporterName: 'Birendra Mahato',
  },
  {
    id: 'rpt-014',
    title: 'Bridge damaged and unsafe for vehicles',
    description: 'The bridge on the river is damaged and unsafe.',
    category: 'Infrastructure',
    subcategory: 'Bridge',
    urgency: 'HIGH',
    affectedPopulation: 2000,
    location: { lat: 23.65, lng: 85.9, name: 'River Bridge, Bokaro', district: 'Bokaro' },
    evidence: [{ id: 'e11', type: 'image', url: '', name: 'bridge.jpg' }],
    status: 'ANALYZED',
    challengeId: 'ch-005',
    createdAt: daysAgo(3),
    reporterName: 'Kavita Singh',
  },
  {
    id: 'rpt-015',
    title: 'Primary health center lacks medical staff',
    description: 'The PHC has no doctor available for weeks.',
    category: 'Healthcare',
    subcategory: 'Staffing',
    urgency: 'HIGH',
    affectedPopulation: 3500,
    location: { lat: 23.4, lng: 85.5, name: 'PHC Block, Ranchi', district: 'Ranchi' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Sanjay Kumar',
  },
  {
    id: 'rpt-016',
    title: 'Crop failure due to pest infestation',
    description: 'Pests have destroyed crops across multiple farms.',
    category: 'Agriculture',
    subcategory: 'Pest Control',
    urgency: 'MEDIUM',
    affectedPopulation: 900,
    location: { lat: 23.2, lng: 85.6, name: 'Rural Farms, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e12', type: 'image', url: '', name: 'crops.jpg' }],
    status: 'SUBMITTED',
    createdAt: daysAgo(2),
    reporterName: 'Phool Devi',
  },
  {
    id: 'rpt-017',
    title: 'Open manholes causing safety hazard',
    description: 'Several manholes are open on the street, dangerous for children.',
    category: 'Public Safety',
    subcategory: 'Infrastructure Hazard',
    urgency: 'HIGH',
    affectedPopulation: 600,
    location: { lat: 23.35, lng: 85.31, name: 'Sector 2, Ranchi', district: 'Ranchi' },
    evidence: [{ id: 'e13', type: 'image', url: '', name: 'manhole.jpg' }],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Deepak Raj',
  },
  {
    id: 'rpt-018',
    title: 'Riverbank erosion threatening homes',
    description: 'The riverbank is eroding and homes are at risk.',
    category: 'Environment',
    subcategory: 'Erosion',
    urgency: 'HIGH',
    affectedPopulation: 1200,
    location: { lat: 22.78, lng: 86.21, name: 'Riverbank, Jamshedpur', district: 'Jamshedpur' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(2),
    reporterName: 'Ramesh Soren',
  },
  {
    id: 'rpt-019',
    title: 'Anganwadi center lacks basic facilities',
    description: 'The anganwadi center has no toilet or drinking water.',
    category: 'Education',
    subcategory: 'Facilities',
    urgency: 'MEDIUM',
    affectedPopulation: 200,
    location: { lat: 23.8, lng: 86.43, name: 'Anganwadi, Dhanbad', district: 'Dhanbad' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Sunita Tudu',
  },
  {
    id: 'rpt-020',
    title: 'Traffic signal not working at main junction',
    description: 'The traffic signal at the main junction is not working.',
    category: 'Transport',
    subcategory: 'Traffic Management',
    urgency: 'MEDIUM',
    affectedPopulation: 8000,
    location: { lat: 23.345, lng: 85.31, name: 'Main Junction, Ranchi', district: 'Ranchi' },
    evidence: [],
    status: 'SUBMITTED',
    createdAt: daysAgo(1),
    reporterName: 'Vikash Ojha',
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: 'ch-001',
    title: 'Urban Road Waterlogging – Ranchi',
    category: 'Infrastructure',
    subcategory: 'Drainage / Road Accessibility',
    location: { name: 'Ranchi', district: 'Ranchi', lat: 23.3441, lng: 85.3096 },
    reportCount: 20,
    affectedPopulation: 2500,
    priority: 87,
    priorityLevel: 'HIGH',
    status: 'MATCHED',
    assignedSolver: 'XYZ Institute of Technology',
    createdAt: daysAgo(5),
    description:
      'Heavy rainfall causes severe waterlogging and road inaccessibility near the main road locality, affecting approximately 2,500 residents and restricting access to schools, healthcare and public transport.',
  },
  {
    id: 'ch-002',
    title: 'School Building Structural Repair – Jamshedpur',
    category: 'Education',
    subcategory: 'Infrastructure',
    location: { name: 'Jamshedpur', district: 'Jamshedpur', lat: 22.8046, lng: 86.2029 },
    reportCount: 8,
    affectedPopulation: 450,
    priority: 72,
    priorityLevel: 'HIGH',
    status: 'PRIORITIZED',
    createdAt: daysAgo(6),
    description:
      'Government school building has structural cracks requiring urgent repair to ensure student safety.',
  },
  {
    id: 'ch-003',
    title: 'Contaminated Water Supply – Dhanbad',
    category: 'Water & Sanitation',
    subcategory: 'Water Quality',
    location: { name: 'Dhanbad', district: 'Dhanbad', lat: 23.7956, lng: 86.4304 },
    reportCount: 12,
    affectedPopulation: 3200,
    priority: 91,
    priorityLevel: 'HIGH',
    status: 'SOLUTION_PROPOSED',
    assignedSolver: 'Environmental Engineering Dept',
    createdAt: daysAgo(4),
    description:
      'Contaminated drinking water supply affecting 3,200 residents, causing waterborne illness.',
  },
  {
    id: 'ch-004',
    title: 'Industrial Air Pollution – Dhanbad',
    category: 'Environment',
    subcategory: 'Air Pollution',
    location: { name: 'Dhanbad', district: 'Dhanbad', lat: 23.7894, lng: 86.4238 },
    reportCount: 15,
    affectedPopulation: 5000,
    priority: 84,
    priorityLevel: 'HIGH',
    status: 'UNDER_VALIDATION',
    createdAt: daysAgo(5),
    description:
      'Factory emissions causing severe air pollution affecting 5,000 nearby residents.',
  },
  {
    id: 'ch-005',
    title: 'Damaged River Bridge – Bokaro',
    category: 'Infrastructure',
    subcategory: 'Bridge',
    location: { name: 'Bokaro', district: 'Bokaro', lat: 23.65, lng: 85.9 },
    reportCount: 6,
    affectedPopulation: 2000,
    priority: 78,
    priorityLevel: 'HIGH',
    status: 'NEW',
    createdAt: daysAgo(3),
    description:
      'A river bridge is structurally damaged and unsafe for vehicles, cutting off access.',
  },
  {
    id: 'ch-006',
    title: 'Primary Health Center Staffing Crisis – Ranchi',
    category: 'Healthcare',
    subcategory: 'Staffing',
    location: { name: 'Ranchi', district: 'Ranchi', lat: 23.4, lng: 85.5 },
    reportCount: 9,
    affectedPopulation: 3500,
    priority: 65,
    priorityLevel: 'MEDIUM',
    status: 'PRIORITIZED',
    createdAt: daysAgo(1),
    description:
      'Primary health center has had no doctor available for weeks, affecting 3,500 residents.',
  },
  {
    id: 'ch-007',
    title: 'Pest Infestation Crop Loss – Ranchi Rural',
    category: 'Agriculture',
    subcategory: 'Pest Control',
    location: { name: 'Ranchi Rural', district: 'Ranchi', lat: 23.2, lng: 85.6 },
    reportCount: 5,
    affectedPopulation: 900,
    priority: 52,
    priorityLevel: 'MEDIUM',
    status: 'NEW',
    createdAt: daysAgo(2),
    description:
      'Pest infestation destroying crops across multiple farms, threatening farmer livelihoods.',
  },
  {
    id: 'ch-008',
    title: 'Open Manhole Safety Hazard – Ranchi',
    category: 'Public Safety',
    subcategory: 'Infrastructure Hazard',
    location: { name: 'Ranchi', district: 'Ranchi', lat: 23.35, lng: 85.31 },
    reportCount: 4,
    affectedPopulation: 600,
    priority: 58,
    priorityLevel: 'MEDIUM',
    status: 'NEW',
    createdAt: daysAgo(1),
    description:
      'Several open manholes on city streets pose serious safety hazards, especially for children.',
  },
  {
    id: 'ch-009',
    title: 'Riverbank Erosion – Jamshedpur',
    category: 'Environment',
    subcategory: 'Erosion',
    location: { name: 'Jamshedpur', district: 'Jamshedpur', lat: 22.78, lng: 86.21 },
    reportCount: 7,
    affectedPopulation: 1200,
    priority: 68,
    priorityLevel: 'MEDIUM',
    status: 'UNDER_VALIDATION',
    createdAt: daysAgo(2),
    description:
      'Riverbank erosion threatening homes of 1,200 residents along the river.',
  },
  {
    id: 'ch-010',
    title: 'Traffic Signal Failure – Ranchi Junction',
    category: 'Transport',
    subcategory: 'Traffic Management',
    location: { name: 'Ranchi', district: 'Ranchi', lat: 23.345, lng: 85.31 },
    reportCount: 3,
    affectedPopulation: 8000,
    priority: 45,
    priorityLevel: 'LOW',
    status: 'NEW',
    createdAt: daysAgo(1),
    description:
      'Traffic signal at the main junction is non-functional, causing congestion and safety risks.',
  },
];

export const mockChallengeDetail: ChallengeDetail = {
  ...mockChallenges[0],
  structuredStatement:
    'Heavy rainfall causes severe waterlogging and road inaccessibility near XYZ locality, affecting approximately 2,500 residents and restricting access to schools, healthcare and public transport.',
  keywords: ['Waterlogging', 'Drainage', 'Road Damage', 'Heavy Rainfall', 'Accessibility'],
  confidence: 94,
  timeline: [
    { id: 't1', label: 'Citizen Reports', status: 'done', date: daysAgo(5) },
    { id: 't2', label: 'AI Analysis', status: 'done', date: daysAgo(5) },
    { id: 't3', label: 'Duplicate Cluster', status: 'done', date: daysAgo(4) },
    { id: 't4', label: 'Government Validation', status: 'done', date: daysAgo(3) },
    { id: 't5', label: 'Priority Assigned', status: 'done', date: daysAgo(3) },
    { id: 't6', label: 'University Matched', status: 'done', date: daysAgo(2) },
    { id: 't7', label: 'Solution Proposal', status: 'current', date: daysAgo(1) },
    { id: 't8', label: 'Pilot', status: 'pending' },
    { id: 't9', label: 'Impact Measurement', status: 'pending' },
  ],
  duplicateCluster: {
    problemId: 'rpt-001',
    totalReports: 20,
    similarity: 92,
    reports: [
      { reportId: 'rpt-001', title: 'Heavy Rainfall Causes Severe Waterlogging on Main Road', similarity: 100, distance: '0 km', date: daysAgo(5), location: 'Main Road, Ranchi', reporter: 'Ravi Kumar' },
      { reportId: 'rpt-002', title: 'Road completely flooded after yesterday rain', similarity: 94, distance: '0.3 km', date: daysAgo(4), location: 'Main Road, Ranchi', reporter: 'Priya Sharma' },
      { reportId: 'rpt-003', title: 'Children unable to reach school because of waterlogging', similarity: 91, distance: '0.5 km', date: daysAgo(3), location: 'School Road, Ranchi', reporter: 'Anita Devi' },
      { reportId: 'rpt-004', title: 'Main road blocked during rainfall', similarity: 89, distance: '0.2 km', date: daysAgo(3), location: 'Main Road, Ranchi', reporter: 'Mohan Singh' },
      { reportId: 'rpt-005', title: 'No proper drainage system in our area', similarity: 87, distance: '0.8 km', date: daysAgo(2), location: 'Sector 4, Ranchi', reporter: 'Suresh Paswan' },
      { reportId: 'rpt-006', title: 'Hospital road flooded, ambulances stuck', similarity: 85, distance: '1.2 km', date: daysAgo(2), location: 'Hospital Road, Ranchi', reporter: 'Dr. K Verma' },
      { reportId: 'rpt-007', title: 'Public transport disrupted due to waterlogging', similarity: 83, distance: '0.4 km', date: daysAgo(1), location: 'Bus Stand, Ranchi', reporter: 'Lakshmi Rao' },
    ],
    unifiedChallengeId: 'ch-001',
  },
  priorityBreakdown: {
    safetyRisk: { score: 25, max: 30 },
    populationImpact: { score: 22, max: 25 },
    recurrence: { score: 18, max: 20 },
    evidence: { score: 12, max: 15 },
    locationRisk: { score: 10, max: 10 },
  },
  priorityExplanation:
    'High priority because the issue affects a large population, has a recurring pattern during heavy rainfall, presents accessibility and safety concerns, and has strong supporting evidence.',
  reports: mockReports.filter((r) => r.challengeId === 'ch-001'),
  evidence: [
    { id: 'ev1', type: 'image', url: '', name: 'flooded_road_1.jpg' },
    { id: 'ev2', type: 'image', url: '', name: 'waterlogging_2.jpg' },
    { id: 'ev3', type: 'image', url: '', name: 'flood.jpg' },
    { id: 'ev4', type: 'image', url: '', name: 'school_road.jpg' },
    { id: 'ev5', type: 'image', url: '', name: 'drain.jpg' },
    { id: 'ev6', type: 'image', url: '', name: 'hospital_road.jpg' },
  ],
  matchedSolvers: [
    {
      id: 's1',
      name: 'XYZ Institute of Technology',
      type: 'university',
      department: 'Civil Engineering + GIS Lab',
      matchScore: 94,
      reasons: [
        'Civil Engineering Expertise',
        'GIS Capability',
        'Drainage Research',
        'Available Team',
        'Local Presence',
        'Previous Similar Projects',
      ],
      description:
        'Recommended because this team has experience in drainage modelling, GIS mapping and urban infrastructure projects.',
    },
    {
      id: 's2',
      name: 'BIT Mesra',
      type: 'university',
      department: 'Environmental Engineering',
      matchScore: 87,
      reasons: [
        'Environmental Engineering',
        'Hydrology Research',
        'Available Team',
        'Previous Urban Projects',
      ],
      description:
        'Strong background in hydrology and environmental engineering with urban project experience.',
    },
    {
      id: 's3',
      name: 'Ranchi University',
      type: 'university',
      department: 'Geography & Urban Planning',
      matchScore: 81,
      reasons: ['Urban Planning', 'Local Knowledge', 'GIS Capability'],
      description:
        'Local university with urban planning expertise and strong community connections.',
    },
    {
      id: 's4',
      name: 'ABC Infrastructure Solutions',
      type: 'industry',
      matchScore: 89,
      reasons: [
        'Drainage Infrastructure',
        'Road Construction',
        'Pilot Experience',
        'Local Operations',
      ],
      description:
        'Industry partner with proven experience in drainage infrastructure and road elevation projects.',
    },
  ],
  solution: {
    challengeId: 'ch-001',
    summary: 'Smart drainage redesign + road elevation improvement',
    approach:
      'Redesign the drainage system with smart sensors, elevate low-lying road sections, and install permeable pavement in critical areas to prevent water accumulation.',
    teamMembers: [
      { id: 'tm1', name: 'Dr. Rajesh Kumar', role: 'Faculty Mentor' },
      { id: 'tm2', name: 'Aman Verma', role: 'Team Lead' },
      { id: 'tm3', name: 'Sneha Roy', role: 'GIS Specialist' },
      { id: 'tm4', name: 'Karan Singh', role: 'Civil Engineer' },
      { id: 'tm5', name: 'Pooja Das', role: 'Research Analyst' },
    ],
    facultyMentor: 'Dr. Rajesh Kumar',
    industryPartner: 'ABC Infrastructure Solutions',
    progress: 68,
    milestones: [
      { id: 'm1', title: 'Research', status: 'completed', progress: 100, dueDate: daysAgo(3), evidenceCount: 4 },
      { id: 'm2', title: 'Site Survey', status: 'completed', progress: 100, dueDate: daysAgo(2), evidenceCount: 6 },
      { id: 'm3', title: 'Prototype', status: 'in_progress', progress: 75, dueDate: daysAgo(0), evidenceCount: 3 },
      { id: 'm4', title: 'Field Testing', status: 'pending', progress: 0, dueDate: daysAgo(-3), evidenceCount: 0 },
      { id: 'm5', title: 'Government Approval', status: 'pending', progress: 0, dueDate: daysAgo(-5), evidenceCount: 0 },
      { id: 'm6', title: 'Pilot', status: 'pending', progress: 0, dueDate: daysAgo(-7), evidenceCount: 0 },
    ],
  },
  pilot: {
    challengeId: 'ch-001',
    status: 'planned',
    startDate: daysAgo(-3),
    location: 'Main Road, Ranchi',
    participants: 2500,
  },
  impact: {
    projectId: 'proj-001',
    impactScore: 82,
    status: 'Pilot Successfully Completed',
    metrics: [
      { id: 'im1', label: 'Road Accessibility', before: 40, after: 95, unit: '%', improvement: 55 },
      { id: 'im2', label: 'Waterlogging Duration', before: 8, after: 1.5, unit: 'hours', improvement: 81 },
      { id: 'im3', label: 'Affected Households', before: 2500, after: 320, unit: '', improvement: 87 },
      { id: 'im4', label: 'Emergency Access', before: 20, after: 90, unit: '%', improvement: 70 },
    ],
    beforeImage: '',
    afterImage: '',
    summary:
      'The pilot successfully improved road accessibility from 40% to 95%, reduced waterlogging duration from 8 hours to 1.5 hours, and reduced affected households from 2,500 to 320.',
  },
};

export const mockSolverMatches: SolverMatch[] = mockChallengeDetail.matchedSolvers;

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    challengeId: 'ch-001',
    challengeTitle: 'Urban Road Waterlogging – Ranchi',
    title: 'Smart Drainage Redesign – Ranchi',
    status: 'ACTIVE',
    progress: 68,
    team: mockChallengeDetail.solution!.teamMembers,
    facultyMentor: 'Dr. Rajesh Kumar',
    industryPartner: 'ABC Infrastructure Solutions',
    createdAt: daysAgo(3),
  },
  {
    id: 'proj-002',
    challengeId: 'ch-003',
    challengeTitle: 'Contaminated Water Supply – Dhanbad',
    title: 'Water Purification System – Dhanbad',
    status: 'PROPOSAL',
    progress: 15,
    team: [
      { id: 'tm6', name: 'Dr. Meera Nair', role: 'Faculty Mentor' },
      { id: 'tm7', name: 'Rohit Agarwal', role: 'Team Lead' },
    ],
    facultyMentor: 'Dr. Meera Nair',
    industryPartner: 'WaterTech Solutions',
    createdAt: daysAgo(2),
  },
  {
    id: 'proj-003',
    challengeId: 'ch-002',
    challengeTitle: 'School Building Structural Repair – Jamshedpur',
    title: 'School Infrastructure Restoration – Jamshedpur',
    status: 'PILOT',
    progress: 85,
    team: [
      { id: 'tm8', name: 'Dr. S. Chatterjee', role: 'Faculty Mentor' },
      { id: 'tm9', name: 'Aniket Bose', role: 'Team Lead' },
    ],
    facultyMentor: 'Dr. S. Chatterjee',
    industryPartner: 'BuildWell Constructions',
    createdAt: daysAgo(5),
  },
];

export const mockImpact: ImpactSummary = mockChallengeDetail.impact!;

export const mockDashboardData: DashboardData = {
  stats: {
    totalReports: 1248,
    validatedChallenges: 326,
    highPriority: 84,
    activeProjects: 47,
    completedPilots: 19,
    impactMeasured: 15,
    verifiedImpactPercent: 82,
  },
  challengesByCategory: [
    { name: 'Infrastructure', value: 98 },
    { name: 'Water & Sanitation', value: 62 },
    { name: 'Healthcare', value: 45 },
    { name: 'Education', value: 38 },
    { name: 'Agriculture', value: 29 },
    { name: 'Environment', value: 27 },
    { name: 'Public Safety', value: 15 },
    { name: 'Transport', value: 12 },
  ],
  priorityDistribution: [
    { name: 'High', value: 84 },
    { name: 'Medium', value: 156 },
    { name: 'Low', value: 86 },
  ],
  reportsByDistrict: [
    { name: 'Ranchi', value: 412 },
    { name: 'Jamshedpur', value: 318 },
    { name: 'Dhanbad', value: 245 },
    { name: 'Bokaro', value: 167 },
    { name: 'Hazaribagh', value: 106 },
  ],
  challengeLifecycle: [
    { stage: 'New', value: 42 },
    { stage: 'Validation', value: 68 },
    { stage: 'Prioritized', value: 95 },
    { stage: 'Matched', value: 73 },
    { stage: 'Solution', value: 31 },
    { stage: 'Pilot', value: 12 },
    { stage: 'Completed', value: 5 },
  ],
  monthlyReports: [
    { month: 'Jan', value: 120 },
    { month: 'Feb', value: 145 },
    { month: 'Mar', value: 180 },
    { month: 'Apr', value: 210 },
    { month: 'May', value: 195 },
    { month: 'Jun', value: 165 },
    { month: 'Jul', value: 233 },
  ],
  mapChallenges: mockChallenges.map((c) => ({
    id: c.id,
    title: c.title,
    lat: c.location.lat,
    lng: c.location.lng,
    priority: c.priority,
    priorityLevel: c.priorityLevel,
    reportCount: c.reportCount,
    affectedPopulation: c.affectedPopulation,
    status: c.status,
    category: c.category,
    district: c.location.district,
  })),
  aiInsights: [
    '12 duplicate clusters detected this week.',
    '8 high-priority challenges are awaiting solver matching.',
    '3 challenges have strong university matches.',
    '2 completed pilots require impact verification.',
  ],
};

export const mockMapData: MapData = {
  challenges: mockDashboardData.mapChallenges,
  hotspots: [
    { name: 'Ranchi', count: 34 },
    { name: 'Jamshedpur', count: 28 },
    { name: 'Dhanbad', count: 21 },
    { name: 'Bokaro', count: 16 },
  ],
};

export const mockAIAnalysis: AIAnalysis = {
  problemId: 'rpt-001',
  structuredStatement:
    'Heavy rainfall causes severe waterlogging and road inaccessibility near XYZ locality, affecting approximately 2,500 residents and restricting access to schools, healthcare and public transport.',
  category: 'Infrastructure',
  subcategory: 'Drainage / Road Accessibility',
  keywords: ['Waterlogging', 'Drainage', 'Road Damage', 'Heavy Rainfall', 'Accessibility'],
  urgency: 'HIGH',
  confidence: 94,
  affectedPopulation: 2500,
  evidenceCount: 2,
};

export const mockDuplicateCluster: DuplicateCluster = mockChallengeDetail.duplicateCluster;

export const mockPriorityScore: PriorityScore = {
  challengeId: 'ch-001',
  total: 87,
  level: 'HIGH',
  breakdown: mockChallengeDetail.priorityBreakdown,
  explanation: mockChallengeDetail.priorityExplanation,
};

export function createMockReport(data: SubmitProblemData): ProblemReport {
  return {
    id: `rpt-${Date.now()}`,
    title: data.title,
    description: data.description,
    category: data.category,
    subcategory: data.subcategory,
    urgency: data.urgency,
    affectedPopulation: data.affectedPopulation,
    location: data.location,
    evidence: data.evidence,
    status: 'SUBMITTED',
    createdAt: new Date().toISOString(),
    reporterName: data.reporterName,
  };
}
